<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DFW2LPTSFH9" name="com.norwex.pcs.CustomerOrder" tests="7" failures="0" timestamp="12 Feb 2016 19:38:56 GMT" time="97.409" errors="1">
  <testcase name="SubmitPayment" time="10.811" classname="com.norwex.pcs.CustomerOrder"/>
  <testcase name="EditOrders" time="18.455" classname="com.norwex.pcs.CustomerOrder"/>
  <testcase name="AddOrders" time="21.257" classname="com.norwex.pcs.CustomerOrder"/>
  <testcase name="UpdateContactInfo" time="19.219" classname="com.norwex.pcs.CustomerOrder">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.norwex.pcs.CustomerOrder.UpdateContactInfo(CustomerOrder.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1240)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </error>
  </testcase> <!-- UpdateContactInfo -->
  <testcase name="NavigateToShoppingSpree" time="0.278" classname="com.norwex.pcs.CustomerOrder"/>
  <testcase name="CompleteOrder" time="7.363" classname="com.norwex.pcs.CustomerOrder"/>
  <testcase name="DeletePay" time="20.026" classname="com.norwex.pcs.CustomerOrder"/>
</testsuite> <!-- com.norwex.pcs.CustomerOrder -->
